name: Build Apple XCFramework

on:
  push:
    tags:
      - "v*"

jobs:
  build-xcframework:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6.1'

      - name: Build (arm64 + x86_64)
        run: |
          swift build -c release --triple arm64-apple-macosx13.0

      - name: Create XCFramework
        run: |
          xcodebuild -create-xcframework \
            -library .build/arm64-apple-macosx/release/libPlaidAPI.a \
            -headers .build/arm64-apple-macosx/release \
            -output PlaidAPI.xcframework

      - name: Zip XCFramework
        run: zip -r PlaidAPI.xcframework.zip PlaidAPI.xcframework

      - name: Compute checksum
        id: checksum
        run: echo "checksum=$(swift package compute-checksum PlaidAPI.xcframework.zip)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PlaidAPI-Apple
          path: PlaidAPI.xcframework.zip

      - name: Generate release snippet
        run: |
          echo '### SwiftPM Binary Target (Apple)
          ```swift
          .binaryTarget(
              name: "PlaidAPI",
              url: "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/PlaidAPI.xcframework.zip",
              checksum: "${{ steps.checksum.outputs.checksum }}"
          )
          ```' > apple-snippet.txt

      - name: Upload snippet
        uses: actions/upload-artifact@v4
        with:
          name: Apple-Snippet
          path: apple-snippet.txt
