name: Build and Package Swift Libraries

on:
  push:
    tags:
      - 'v*.*.*' # Only runs on version tags

jobs:
  build-macos:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4

      - name: Build macOS static libraries
        run: |
          swift build -c release
          mkdir -p out/macos
          find .build -name "*.a" -exec cp {} out/macos/ \;

      - name: Create XCFramework
        run: |
          mkdir -p build/include
          # If your library has headers, copy them here
          # cp -R Sources/MyLib/include/* build/include/
          xcodebuild -create-xcframework \
            -library out/macos/libPlaidAPI.a \
            -headers build/include \
            -output out/PlaidAPI.xcframework
          cd out
          zip -r ../PlaidAPI-macOS.xcframework.zip PlaidAPI.xcframework

      - uses: actions/upload-artifact@v4
        with:
          name: macos-xcframework
          path: PlaidAPI-macOS.xcframework.zip

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Linux static archives
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t PlaidAPI-builder \
            -f Dockerfile \
            --output type=local,dest=out .
          cd out && tar -czf ../PlaidAPI-Linux.tar.gz .

      - uses: actions/upload-artifact@v4
        with:
          name: linux-static-libs
          path: PlaidAPI-Linux.tar.gz

  release:
    needs: [build-macos, build-linux]
    runs-on: ubuntu-22.04
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/macos-xcframework/PlaidAPI-macOS.xcframework.zip
            artifacts/linux-static-libs/PlaidAPI-Linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
